name: Binder
on:
  push:
    branches:
      - master

jobs:
  binder:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: cache binder build on mybinder.org
        uses: machine-learning-apps/repo2docker-action@0.2
        with:
          NO_PUSH: true
          IMAGE_NAME: ${{ toLower(format('{0}/{1}', github.repository_owner, github.event.repository.name)) }}
          MYBINDERORG_TAG: ${{ github.event.ref }}